name = "raw-hp"
main = "src/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"

[observability]
enabled = true

[[send_email]]
name = "SEB"
destination_address = "rawizuoshima@gmail.com"
